### PR TITLE
Update to latest code from cookie cutter

### PR DESCRIPTION
**Pull request by jovial**
Using: https://github.com/mrlesmithjr/cookiecutter-ansible-role/commit/cf54787ae3a842bf5612ee58bacd965b7237f22d

### CODE REVIEW

**Comment by jovial** [comment]
Seems there is an issue creating the PID file: https://github.com/mrlesmithjr/ansible-chrony/pull/10/checks?check_run_id=2403119237#step:5:1795

**Comment by jovial** [comment]
@mrlesmithjr Not sure how requirements-dev.txt  and requirements.txt should be updated. My manual changes have broken travis :(

**Comment by mrlesmithjr** [comment]
I think the issue of the requirements is from me updating the Cookiecutter template recently. I'll get this resolved on the template.

**Comment by mrlesmithjr** [comment]
@jovial The Python requirements issue should be resolved in the original Cookiecutter template.

**Comment by jovial** [comment]
Any idea why ubuntu fails on travis?

https://travis-ci.org/github/mrlesmithjr/ansible-chrony/jobs/768391546#L621

**Comment by mrlesmithjr** [comment]
Not sure. I am debating disabling Travis for all testing and sticking with GitHub actions.

**Comment by mrlesmithjr** [comment]
@jovial - Go ahead and delete `CHANGELOG.md` from the repo to `pre-commit` checks to pass. I am working on an alternative to `CHANGELOG.md` anyways.

**Pull request merged**
