### PR TITLE
improve apt cache reliability

### PR DESCRIPTION
**Pull request by DisasteR**
## Description

Handle cache refresh to avoid old cache errors.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mrlesmithjr** [comment]
@DisasteR - This change will not work for non-Debian systems unfortunately because of the use of the `package` module. So, the structure of the task(s) will need to be modified.

**Comment by DisasteR** [comment]
@mrlesmithjr you are right missed that.
They all seems to support update_cache. Problem is with cache_valid_time.
i'll try something maybe omit values by ansible os... What do you think about that ?
Or i could check for ansible_pkg_mgr facts. What do you prefer ?

**Comment by DisasteR** [comment]
Opted for ansible_pkg_mgr test as it is more safe to check to add specific apt args.

**Comment by DisasteR** [comment]
@mrlesmithjr are you ok with that ?
will you accept a PR to set `makestep 1.0 3` as default and allowing editing ?

**Comment by DisasteR** [comment]
@mrlesmithjr any news ?

**Pull request merged**
